version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker-compose-php-dockerfile
    image: boxbilling/php
    container_name: app-boxbilling
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: docker-compose-nginx-dockerfile
    image: boxbilling/nginx
    container_name: webserver-boxbilling
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: webserver
      SERVICE_TAGS: dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db-boxbilling
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_ROOT_PASSWORD: xxxxxx
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-config/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local